name: Blender daily build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - main
      - 'run-ci/**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Blender source
        uses: actions/checkout@v4
        with:
          repository: TechnoHT/blender
          path: C:\blender

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2

      - name: Set up Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: vc142

      - name: Download Blender libraries
        run: |
          cd C:\blender\blender
          make update

      - name: Compile Blender
        run: |
          cd C:\blender\blender
          make

      - name: Compress Blender build output
        run: |
          Compress-Archive -Path C:\blender\build_windows_Full_x64_vc17_Release\bin -DestinationPath blender_build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: blender-build
          path: blender_build.zip
